# Kong API Gateway Configuration for Supabase
_format_version: "2.1"

services:
  - name: postgrest
    url: http://rest:3000
    routes:
      - name: postgrest-route
        paths:
          - /rest/v1/
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Client-Info
          exposed_headers:
            - X-Total-Count
          credentials: true
          max_age: 3600

  - name: realtime
    url: http://realtime:4000
    routes:
      - name: realtime-route
        paths:
          - /realtime/v1/
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          credentials: true

  - name: meta
    url: http://meta:8080
    routes:
      - name: meta-route
        paths:
          - /pg/
        strip_path: true
